"""
美股常用股票名稱對照表
手動維護的常見美股代號和名稱對照
"""

US_STOCK_NAMES = {
    # 科技巨頭
    "AAPL": "蘋果",
    "MSFT": "微軟",
    "GOOGL": "Google",
    "GOOG": "Google",
    "AMZN": "亞馬遜",
    "META": "Meta",
    "NVDA": "輝達",
    "TSLA": "特斯拉",
    "TSM": "台積電ADR",
    
    # 科技股
    "NFLX": "Netflix",
    "INTC": "英特爾",
    "AMD": "超微",
    "QCOM": "高通",
    "AVGO": "博通",
    "CSCO": "思科",
    "ORCL": "甲骨文",
    "ADBE": "Adobe",
    "CRM": "Salesforce",
    "IBM": "IBM",
    "PYPL": "PayPal",
    "SQ": "Block",
    "SHOP": "Shopify",
    "SNOW": "Snowflake",
    "PLTR": "Palantir",
    "U": "Unity",
    "COIN": "Coinbase",
    "SPOT": "Spotify",
    "UBER": "優步",
    "LYFT": "Lyft",
    "ABNB": "Airbnb",
    "DOCU": "DocuSign",
    "ZM": "Zoom",
    "CRWD": "CrowdStrike",
    "DDOG": "Datadog",
    "NET": "Cloudflare",
    "MDB": "MongoDB",
    "OKTA": "Okta",
    "TWLO": "Twilio",
    "AFRM": "Affirm",
    "SOFI": "SoFi",
    "HOOD": "Robinhood",
    "RBLX": "Roblox",
    "RIVN": "Rivian",
    "LCID": "Lucid",
    "NIO": "蔚來",
    "XPEV": "小鵬",
    "LI": "理想",
    "BABA": "阿里巴巴",
    "JD": "京東",
    "PDD": "拼多多",
    "BIDU": "百度",
    "BILI": "嗶哩嗶哩",
    "TME": "騰訊音樂",
    "NTES": "網易",
    "VIPS": "唯品會",
    "IQ": "愛奇藝",
    "DIDI": "滴滴",
    
    # 半導體
    "MU": "美光",
    "AMAT": "應材",
    "LRCX": "拉姆研究",
    "KLAC": "科磊",
    "ASML": "艾司摩爾",
    "TXN": "德州儀器",
    "MRVL": "Marvell",
    "ON": "安森美",
    "SWKS": "Skyworks",
    "QRVO": "Qorvo",
    "MPWR": "Monolithic",
    "ARM": "ARM",
    "SMCI": "超微電腦",
    "MU": "美光科技",
    
    # 金融
    "JPM": "摩根大通",
    "BAC": "美國銀行",
    "WFC": "富國銀行",
    "C": "花旗",
    "GS": "高盛",
    "MS": "摩根士丹利",
    "V": "Visa",
    "MA": "萬事達",
    "AXP": "美國運通",
    "BRK.A": "波克夏",
    "BRK.B": "波克夏",
    "BLK": "貝萊德",
    "SCHW": "嘉信",
    
    # 消費/零售
    "WMT": "沃爾瑪",
    "COST": "好市多",
    "HD": "家得寶",
    "TGT": "Target",
    "LOW": "勞氏",
    "NKE": "耐吉",
    "SBUX": "星巴克",
    "MCD": "麥當勞",
    "KO": "可口可樂",
    "PEP": "百事可樂",
    "DIS": "迪士尼",
    "NWSA": "新聞集團",
    
    # 醫療
    "JNJ": "嬌生",
    "UNH": "聯合健康",
    "PFE": "輝瑞",
    "MRK": "默沙東",
    "ABBV": "艾伯維",
    "LLY": "禮來",
    "TMO": "賽默飛",
    "ABT": "雅培",
    "BMY": "百時美施貴寶",
    "AMGN": "安進",
    "GILD": "吉利德",
    "MRNA": "Moderna",
    "BNTX": "BioNTech",
    
    # 能源
    "XOM": "埃克森美孚",
    "CVX": "雪佛龍",
    "COP": "康菲石油",
    "SLB": "斯倫貝謝",
    "OXY": "西方石油",
    
    # 工業
    "BA": "波音",
    "CAT": "卡特彼勒",
    "DE": "迪爾",
    "GE": "奇異",
    "HON": "霍尼韋爾",
    "UPS": "UPS",
    "FDX": "聯邦快遞",
    "LMT": "洛克希德馬丁",
    "RTX": "雷神",
    "NOC": "諾斯洛普格魯曼",
    
    # ETF
    "SPY": "標普500 ETF",
    "QQQ": "納指100 ETF",
    "VOO": "Vanguard S&P 500",
    "VTI": "全美股市 ETF",
    "IWM": "羅素2000 ETF",
    "DIA": "道瓊 ETF",
    "ARKK": "ARK創新 ETF",
    "SOXL": "半導體3X ETF",
    "TQQQ": "納指3X ETF",
    "SQQQ": "納指反向3X",
    "VGT": "科技股 ETF",
    "SMH": "半導體 ETF",
}


def get_us_stock_name(symbol: str) -> str:
    """取得美股名稱"""
    return US_STOCK_NAMES.get(symbol.upper(), "")
